---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: just_install_packages
    templates:
    - name: just_install_packages
      release: minio-dist
    instances: 4
    persistent_disk: 1024
    resource_pool: small_z1
    networks: (( param "Please configure the networks for this job" ))

networks: (( param "Please configure the global network definitions for this Deployment" ))

properties: {}
