#!/bin/bash

set -e -u

RUN_DIR=/var/vcap/sys/run/minio-gateway
LOG_DIR=/var/vcap/sys/log/minio-gateway
TMP_DIR=/var/vcap/sys/tmp/minio-gateway
STORE_DIR=/var/vcap/store/minio-gateway
mkdir -p ${RUN_DIR} ${LOG_DIR} ${TMP_DIR} ${STORE_DIR}

PIDFILE=${RUN_DIR}/minio-gateway.pid

case $1 in

  start)
    export LANG=en_US.UTF-8
    export MINIO_ACCESS_KEY=<%= p("access_key") %>
    export MINIO_SECRET_KEY=<%= p("secret_key") %>

    echo $$ > $PIDFILE

    exec /var/vcap/packages/minio/minio gateway \
      --address "0.0.0.0:<%=p("port")%>" \
      <%= p("gateway_type") %> \
      >>  ${LOG_DIR}/minio_gateway.stdout.log \
      2>> ${LOG_DIR}/minio_gateway.stderr.log

    ;;

  stop)
    if [ -f $PIDFILE ]; then
      kill -9 `cat $PIDFILE` || true
      rm -f $PIDFILE
    fi

    ;;

  *)
    echo "Usage: ctl {start|stop}"

    ;;

esac
exit 0
